### ISSUE TITLE
liberfa version number test too tight 

### ISSUE THREAD

**Issue by olebole** [liberfa/pyerfa#52]
On Debian, we have pyerfa and erfa in separate packages and update them independently (and by different people).  However, there is one test that fails when doing so: https://github.com/liberfa/pyerfa/blob/822d095c96e8203d222be23450beb83dc792b876/erfa/tests/test_erfa.py#L37-L43

Specifically, I now updated erfa to 1.7.1, and pyerfa-1.7.0 [fails on this test](https://ci.debian.net/data/autopkgtest/testing/amd64/p/pyerfa/7117273/log.gz) now. It would IMO be better if the test would just check the backward compatibility, i.e. that pyerfa uses a version that is too old (incompatible) with the current version. But in principle, if all other tests succeed (and have sufficient code coverage) there would be no need to have this test at all?

Having too strong dependencies on the package (even for testing) makes it much harder to maintain them.

Cc: @avalentino as the Debian maintainer of pyerfa

**Comment by bnavigator** [comment]
+1 from [openSUSE](https://build.opensuse.org/package/show/devel:languages:python:numeric/python-pyerfa)

**Comment by bnavigator** [comment]
BTW, the last commit on master 822d095 makes the same fail even with bundled erfa 1.7.1

The test reveals a very confusing naming convention: How to distinguish between pyerfa version and erfa version? Unless you really want to pin to equal versions for both packages, the attributes should have a more declarative name. Otherwise a strict pin on the requirements and coincident releases would be needed. In that case, did you just forget to mark the tag https://github.com/liberfa/pyerfa/releases/tag/v1.7.1 as release?

**Comment by bnavigator** [comment]
According to https://github.com/liberfa/pyerfa/pull/39#issuecomment-654339788, differing versions between liberfa and pyerfa should be okay. Skipping the test for now.

**Comment by avalentino** [comment]
In liberfa/pyerfa#53 the test have been changed to perform tight version checking only in case of embedded liberfa.
